version: '3.8'

services:
  planning-poker:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TRUST_PROXY=true
      - API_RATE_WINDOW_MS=60000
      - API_RATE_MAX=180
    restart: unless-stopped
    container_name: planning-poker-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s