version: '3.8'

services:
  planning-poker:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: planning-poker-app